## YAML Template.
---
server:
    port: 9000
    
spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
            mvc:
                routes:
                    - id: produk-service
                      uri: lb://produk-service
                      predicates:
                          - Path=api/v1/product/**
                          
                    - id: pembayaran-service
                      uri: lb://pembayaran-service
                      predicates:
                          - Path=api/v1/pembayaran/** 
                          
                    - id: order-service
                      uri: lb://order-service
                      predicates:
                          - Path=api/v1/order/** 
                                                   
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost